services:
  - type: web
    name: telegram-php-translator-bot
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
    dockerfilePath: Dockerfile
